name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # required for provenance attestation & trusted publishing OIDC
    steps:
      - uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Publish to npm with provenance
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn npm publish --access public --provenance
